### ISSUE TITLE
[BUG] Not finding results for shows released this month, despite episodes being available and correctly titled on all servers.

### ISSUE THREAD

**Issue by TheGuyWhoo** [umbrellaplug/umbrellaplug.github.io#244]
### Bug

So this is specifically regarding plex shares, idk about debrid and stuff. I have tested this on two devices with the same result. Using version 6.6.18 and 1.0.10 coco. kodi 19.3

You can test it on the latest episodes of grey's anatomy and station 19.

### Expected Result

find sources

### Steps To Reproduce

Scrape any episode released this month

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

19.3, pc and tv box. Umbrella log empty.

Coco log

    [2023-03-05 17:02:34] [COLOR red][ COCOSCRAPERS ERROR ][/COLOR]: PLEXSHARE - Exception: 
    Traceback (most recent call last):
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 449, in _make_request
        six.raise_from(e, None)
      File "<string>", line 3, in raise_from
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 444, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
        response.begin()
      File "/usr/lib/python3.8/http/client.py", line 316, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/usr/lib/python3.8/socket.py", line 669, in readinto
        return self._sock.recv_into(b)
      File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "/usr/lib/python3.8/ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
        resp = conn.urlopen(
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
        retries = retries.increment(
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 550, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/packages/six.py", line 770, in reraise
        raise value
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
        httplib_response = self._make_request(
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 451, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 340, in _raise_timeout
        raise ReadTimeoutError(
    urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='88-99-2-18.868417fdcb9f4eb1a43bdbfdc74227f3.plex.direct', port=32404): Read timed out. (read timeout=10)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.kodi/addons/script.module.cocoscrapers/lib/cocoscrapers/sources_cocoscrapers/hosters/plexshare.py", line 78, in get_sources
        try: results = requests.get(url,timeout=10)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
        r = adapter.send(request, **kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 532, in send
        raise ReadTimeout(e, request=request)
    requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='88-99-2-18.868417fdcb9f4eb1a43bdbfdc74227f3.plex.direct', port=32404): Read timed out. (read timeout=10)
     (NORMALIZED by log_utils.log())
    [2023-03-05 17:02:34] [COLOR red][ COCOSCRAPERS ERROR ][/COLOR]: PLEXSHARE - Exception: 
    Traceback (most recent call last):
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 449, in _make_request
        six.raise_from(e, None)
      File "<string>", line 3, in raise_from
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 444, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
        response.begin()
      File "/usr/lib/python3.8/http/client.py", line 316, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/usr/lib/python3.8/socket.py", line 669, in readinto
        return self._sock.recv_into(b)
      File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "/usr/lib/python3.8/ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
        resp = conn.urlopen(
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
        retries = retries.increment(
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 550, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/packages/six.py", line 770, in reraise
        raise value
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
        httplib_response = self._make_request(
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 451, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
      File "/home/user/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 340, in _raise_timeout
        raise ReadTimeoutError(
    urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='142-198-44-196.664fc44fddbb4a25b7c5ba31750ba5a4.plex.direct', port=42400): Read timed out. (read timeout=10)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/.kodi/addons/script.module.cocoscrapers/lib/cocoscrapers/sources_cocoscrapers/hosters/plexshare.py", line 78, in get_sources
        try: results = requests.get(url,timeout=10)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
        return session.request(method=method, url=url, **kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
        r = adapter.send(request, **kwargs)
      File "/home/user/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 532, in send
        raise ReadTimeout(e, request=request)
    requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='142-198-44-196.664fc44fddbb4a25b7c5ba31750ba5a4.plex.direct', port=42400): Read timed out. (read timeout=10)
     (NORMALIZED by log_utils.log())

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by TheGuyWhoo** [comment]
Edit: initially added the wrong log.

**Comment by umbrellaplug** [comment]
This snippet of log doesnt tell me anything relevant. You're having connection errors. That's about it.

**Comment by TheGuyWhoo** [comment]
That's actually the full log and I am 100% not having connection issues
since all other episodes are finding sources, as long as they aren't from
this month.

**Comment by TheGuyWhoo** [comment]
Can you reproduce issue?

**Comment by TheGuyWhoo** [comment]
This is actually so baffling. Episodes released after the first of this
month is saying no stream, despite it being available on several servers.

**Comment by umbrellaplug** [comment]
I have no issues with getting results from multiple servers from this month.

**Comment by TheGuyWhoo** [comment]
Wow, I'm thrown by the awful attitude. Thank you for taking a look and
confirming that the issue is on my end, though.

I'm not sure why you keep insisting that it's a partial log mate, that is
literally a ctrl-a copy and paste. But okay. Like I said thanks for taking
a look.

**Comment by TheGuyWhoo** [comment]
I'll take a video and show you if you're willing to take a look at the
issue, I mean if you can't be bothered to take a look anyways I don't want
to waste my time, but yeah I can take a video showing you how it only finds
sources for episodes prior to this month, all my filtering setups(which is
default btw), an empty umbrella log and an identical coco log. This
behavior is present and identical on both PC and android box.

**Comment by TheGuyWhoo** [comment]
I just reproduced this on my phone using nexus. Just to reiterate this is
specifically using plex shares. I'm willing to share literally any piece of
information you need, but as I've stated the umbrella log is empty and the
coco log is exactly as what I provided... I'm sorry to be annoying and I'm
sorry if it seemed like I was  being uncooperative or something, I just
really love this addon.

**Comment by umbrellaplug** [comment]
Please point coco scrapers and umbrella to kodi.log and upload the Kodi.log or a link to it after searching for an episode you know is on one of the servers. The very limited logs you have listed only show a connection timeout. 

Cocoscrapers is not maintained by me so if it seems like I have an attitude it's because I'm being asked to troubleshoot a project I didn't write with limited information for an issue I'm unable to duplicate. But I get it, the scraper dev is impossible to get in touch with so you're opening issues with the only person you know can help. 

What are you searching for? Do you have access to the actual Plex server? Can you access the troubleshoot tab on the Plex server to select optimize database?

**Comment by TheGuyWhoo** [comment]
I've tried on the latest episode of several shows now, including last of us, grey's anatomy, station 19, abbott elementary etc. All of those are available on several of the severs which I'm on, all of which return results for episodes from before this month.

I do not have access to any of the servers, I am just a share user.

Kodi log:

[kodi.log](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10907780/kodi.log)
